### ISSUE TITLE
webpage icons to show on tabs

### ISSUE THREAD

**Issue by dinotheextinct** [MiguelRAvila/SimplerentFox#17]
Hey,
is it somehow possible to have the icons show on the tabs? Otherwise its kinda useless to have tabs anyway if you only have text imo.

**Comment by MiguelRAvila** [comment]
Hey! @dinotheextinct , off course is posible to add them again. You just have to uncoment this line of code in one of the no-compressed files:

```css
hbox.tab-content .tab-icon-image {
    display: none !important;
}
```
You just have to delete that lines or comment them like this:

```css
/*
hbox.tab-content .tab-icon-image {
    display: none !important;
}
*/
```
If you have another problem just comment it! Hope this works for you
