### ISSUE TITLE
Transparent URL bar

### ISSUE THREAD

**Issue by Kailash-777** [MiguelRAvila/SimplerentFox#19]
This may be a really stupid question but my URL bar is transparent. How do I make it opaque?
![2020-12-27_01-44_1](https://user-images.githubusercontent.com/34036909/103158577-3cea4100-47e5-11eb-934a-94f950227ac2.png)

**Comment by MiguelRAvila** [comment]
Hey! @Kailash-777 you have to change this:

```css
#urlbar-background {
    background: transparent !important;
    border: transparent !important;
    animation: none !important;
}
```
The value transparent for another value like rgba(20, 20, 20, 0.8);
Hope this works for you!
