### ISSUE TITLE
Show favicon

### ISSUE THREAD

**Issue by kovetskiy** [MiguelRAvila/SimplerentFox#22]
Hey! Thank you for sharing your awesome work! How can I get favicons back with userChrome_OneLine?

**Comment by MiguelRAvila** [comment]
Hi! @kovetskiy  You have to delete (or comment) this section:

```css
/* This one clears the tabs icon when they're not pinned  */
.tabbrowser-tab:not([pinned]) .tab-icon-image {
    display: none !important;
}
```
Hope this works for you!
