### ISSUE TITLE
Collapsible vertical tab bar

### ISSUE THREAD

**Issue by Kabouik** [MiguelRAvila/SimplerentFox#3]
SimplerentFox looks really great, I'll give it a try soon! However, for personal convenience, I would prefer a collapsible vertical tab bar, as it allows having more tabs visible without truncating them too much, plus it gains some vertical space.

There's an example on this [video](https://youtu.be/8PnDZtKzsSc?t=58) I put up lately to better illustrate what I have in mind (even though it's on a phone here, I use the same Firefox CSS on desktop, just don't have a video for it yet). Moving the tab bar to the side also frees some space vertically, and I also hid the address bar and title bar so that the content uses all available screen estate without going fullscreen.

This is based on the Tree Style Tabs addon, and I use the (messy with probably a few conflicts) CSS code at the bottom of this post, that is now partly broken after a recent Firefox update.

Do you think I could use use the same side bar feature and hide address and title bars using this approach in SimplerentFox, or do you foresee many conflicts?

In Tree Style Tabs options:
```css
/* Desaturate favicons in inactive tab */
.tab:not(.active) .favicon {
  filter: grayscale(1) brightness(0.7) contrast(1) invert(1);
}

/* Hide background of inactive tabs when tab bar is collapsed */
.tab:not(.active) {
  border-left: 25px solid;
  border-color: var(--theme-colors-frame);
}

/* Push tab labels slightly to the right so they're completely hidden in collapsed state */
tab-item .label {
    margin-left: 15px;
    font-size: 95%
}

/* Move favicons to the left */
.tab .favicon {
  margin-left: -10px;
}

.tab.active .favicon {
  margin-left: -7px !important;
}

/* Move .twisty to the right of favicons and adjust margins to reduce space on the left. */
tab-item .twisty {
    margin-left: -4px;
    margin-right: 0px;
    left: 22px;
}

/* Background color of the empty tab bar */
:root,
#background {
  background: var(--theme-colors-frame);
}

/* Show title of unread tabs with red and italic font */
.tab.unread .label {
  color: #5294E2 !important;
  font-style: italic !important;
}

/* Add private browsing indicator per tab */
.tab.private-browsing .label:before {
  content: "🕶";
}

/* Hide border on tab bar, force its state to 'scroll', adjust margin-left for width of scrollbar. */ 
#tabbar {
  border: 0; overflow-y: scroll !important; margin-left: -14px !important; scrollbar-width: auto;
}

/* Hide close buttons on tabs. */
tab-item .closebox {
  visibility: collapse;
}

/* Hide sound playing/muted button. */
.sound-button::before {
  display: none !important;
}

/* Hide new tab button and eliminate dead space on bottom */
.newtab-button-box {
  display: none;
}
#tabbar {
  bottom: 0 !important;
}
```

In userChrome.css:
```css
 /* FIX CONTEXT MENU DISAPPEARING IMMEDIATELY */
#contentAreaContextMenu {
  margin: 5px 0 0 5px
}

/* HIDE TITLE BAR */
#titlebar {
  visibility: collapse;
}

/* HIDE NATIVE TABS */
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar > .toolbar-items {
  opacity: 0;
  pointer-events: none;
}

#main-window:not([tabsintitlebar="true"]) #TabsToolbar {
    visibility: collapse !important;
}

/* AUTO-HIDE URL-BAR AND SHOW ON HOVER (SWIPE FROM OUTSIDE TOP OF THE WINDOW) OR FOCUS WITH CTRL+L */
#nav-bar:not([customizing="true"]):not([inFullscreen]) {
	min-height: 35px !important;
	max-height: 102px !important;
	margin-top: 2px !important;
	margin-left: 28px !important;
 	margin-right: 12px !important;
	margin-bottom: -85px !important;
  border-top: 0px !important;
	border-bottom: 50px solid transparent !important; /* This expands the hover area when the bar is visible */
	background-clip: content-box; /* This together with border-bottom expands the hover area when the bar is visible */
    /* Chose one of either options below
    Option 2: not recommended because it makes the whole
    invisible bar (+ its invisible border) hoverable, which may
    prevent clicking on website buttons located on top
    Option 1: does not cause this issue, but requires accurate hovering on the top
    border of the Firefox window, or swiping from outside the window to expand the bar
    /* Option 1 */
       z-index: -5 !important;
    /* Option 2 */
       /* 
       opacity: 0;
       z-index: 5 !important;
       */
}

#navigator-toolbox:hover:not([inFullscreen]) :-moz-any(#nav-bar),
#navigator-toolbox:focus-within :-moz-any(#nav-bar) {
  margin-top: -17px !important;
  border-top: 20px solid var(--toolbar-bgcolor) !important;
  box-sizing: border-box !important;
  z-index: 5 !important;
	opacity: 1;
}

#urlbar {
	border: 0 !important;
	padding-left: 10px;
	padding-right: 10px;
	border-radius: 1px 1px 1px 1px !important;
	background-color: #0000002d !important;
	box-shadow: none !important;
	text-align: center !important;
}

#navigator-toolbox {
	--toolbar-bgcolor: rgba(0,0,0,.8);
	--urlbar-separator-color: transparent;
	--lwt-toolbarbutton-icon-fill: var(--theme-colors-icons);
	--lwt-toolbar-field-background-color: transparent !important;
	--lwt-toolbar-field-border-color:  transparent !important;
	--lwt-toolbar-field-focus: transparent !important;
	--toolbar-field-focus-border-color: #77777773 !important;
}

/* Hide toolbar in fullscreen mode */
/*
#nav-bar[inFullscreen="true"] {
  visibility: collapse;
}
*/

/* AUTOHIDE BOOKMARK BAR */
#PersonalToolbar {
  --uc-bm-height: 20px; /* Might need to adjust if the toolbar has other buttons */
}

:root[uidensity="compact"] #PersonalToolbar {
  --uc-bm-padding: 1px
}
:root[uidensity="touch"] #PersonalToolbar {
  --uc-bm-padding: 6px
}

#PersonalToolbar:not([customizing="true"]):not([inFullscreen]) {
  margin-bottom: calc(2px - var(--uc-bm-height) - 2 * var(--uc-bm-padding));
  margin-left: 28px !important;
  margin-right: 12px !important;
  padding-top: 10px;
  width: calc(100% - 40px);
  top: 35px; /* Must be the same as the min-height of the URL/navbar */
  display: block;
  z-index: 5 !important;
  opacity: 1;
}
  
#PlacesToolbarItems > .bookmark-item {
	padding-block: var(--uc-bm-padding) !important;
  color: var(--theme-colors-icons);
  font-size: 80%;
  font-family: monospace;
}

/* Select bookmark bar behavior */
/* Comment out either one of these to disable that behavior */
  /* Show when urlbar is focused */
  #nav-bar:focus-within + #PersonalToolbar {
    position: absolute !important;
  }
  /* Show when cursor is over the toolbar area */
  #navigator-toolbox:hover > #PersonalToolbar{
    position: absolute !important;
  }

/* REMOVE FAVICONS FROM BOOKMARK BAR */
.bookmark-item > .toolbarbutton-icon {
    display: none !important;
}

#PlacesToolbarItems > .bookmark-item > .toolbarbutton-icon[label]: {
    margin-inline-end: 0px !important;
}


/* AUTOHIDE VERTICAL TAB BAR USING TREE STYLE TABS EXTENSION */
/* Hide splitter, when using Tree Style Tab. */
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] + #sidebar-splitter {
    display: none !important;
}

/* Hide sidebar header, when using Tree Style Tab. */
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
    visibility: collapse;
}

/* Shrink sidebar until hovered, when using Tree Style Tab. */
:root {
    --thin-tab-width: 28px;
}

:root {
    --wide-tab-width: 260px;
}

#sidebar-box:not([sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"]) {
    min-width: var(--wide-tab-width) !important;
    max-width: none !important;
}
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] {
    overflow: hidden !important;
    position: relative !important;
    transition: all 200ms !important;
    min-width: var(--thin-tab-width) !important;
    max-width: var(--thin-tab-width) !important;
    z-index: 1;
}

#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"]:hover,
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar {
    transition: all 200ms !important;
    min-width: var(--wide-tab-width) !important;
    max-width: var(--wide-tab-width) !important;
    margin-right: calc((var(--wide-tab-width) - var(--thin-tab-width)) * -1) !important;
    z-index: 1;
}

/* SHOW TAB FAVICONS IN GRAYSCALE EXCEPT FOR ACTIVE TAB */
#tab > .tab-icon, .tab-icon-image {
  filter: grayscale(1) brightness(0.5) contrast(1) invert(1) !important; /* Remove invert(1) to make it dark */
}

/* ############################################################# */
/* CSS FOR TREE STYLE TABS TO PASTE IN THE EXTENSION PREFERENCES */
/* ############################################################# */

/* Desaturate favicons in inactive tab */
/*
.tab:not(.active) .favicon {
  filter: grayscale(1) brightness(0.7) contrast(1) invert(1);
}
*/


/* Hide background of inactive tabs when tab bar is collapsed */
/*
.tab:not(.active) {
  border-left: 25px solid;
  border-color: var(--theme-colors-frame);
}
*/

/* Push tab labels slightly to the right so they're completely hidden in collapsed state */
/*
tab-item .label {
    margin-left: 15px;
    font-size: 95%
}
*/

/* Move favicons to the left */
/*
.tab .favicon {
  margin-left: -10px;
}

.tab.active .favicon {
  margin-left: -7px !important;
}
*/

/* Move .twisty to the right of favicons and adjust margins to reduce space on the left. */
/*
tab-item .twisty {
    margin-left: -4px;
    margin-right: 0px;
    left: 22px;
}
*/

/* Background color of the empty tab bar */
/*
:root,
#background {
  background: var(--theme-colors-frame);
}
*/

/* Show title of unread tabs with blue and italic font */
/*
.tab.unread .label {
  color: #5294E2 !important;
  font-style: italic !important;
}
*/

/* Add private browsing indicator per tab */
/*
.tab.private-browsing .label:before {
  content: "🕶";
}
*/

/* Hide border on tab bar, force its state to 'scroll', adjust margin-left for width of scrollbar. */
/*
#tabbar {
  border: 0; overflow-y: scroll !important; margin-left: -14px !important; scrollbar-width: auto;
}
*/

/* Hide close buttons on tabs. */
/*
tab-item .closebox {
  visibility: collapse;
}
*/

/* Hide sound playing/muted button. */
/*
.sound-button::before {
  display: none !important;
}
*/

/* Hide new tab button and eliminate dead space on bottom */
/*
.newtab-button-box {
  display: none;
}
#tabbar {
  bottom: 0 !important;
}
*/
```
